.TH "TypusPocus" "6" "0.4.2  20/03/2010" "Facundo Batista" ""
.SH "NAME"
.LP 
Typus Pocus \- Type spells and be the greatest magician.
.SH "SYNTAX"
.LP 
typuspocus
.SH "DESCRIPTION"
.LP 
Typus Pocus is a game about a magician that needs to cast spells typing them to go through his particular adventure.
.LP 
It was created during the seven days of PyWeek FIXME, international competition that this game won.
.SH "AUTHORS"
.LP 
Alecu, FacundoBatista, LeitoMonk, LucioTorre, NubIs, PabloZ, Riq, Tenuki, nrm; from the Python Argentina group.
.SH "SEE ALSO"
.LP 
FIXME: URL typus
.LP 
FIXME: pyweek gano
