.TH "TypusPocus" "6" "March 2010" "Facundo Batista" ""
.SH NAME
typuspocus \- Type spells and be the greatest magician.
.SH SYNTAX
typuspocus
.SH DESCRIPTION
Typus Pocus is a game about a magician that needs to cast spells typing them to go through his particular adventure.
.LP 
It was created during the seven days of PyWeek 3, international competition that this game won.
.SH AUTHORS
Alecu, FacundoBatista, LeitoMonk, LucioTorre, NubIs, PabloZ, Riq, Tenuki, nrm; from the Python Argentina group.
.SH SEE ALSO
https://edge.launchpad.net/typuspocus
.LP 
http://www.pyweek.org/3/
